import { jsPDF } from "jspdf";

type AgreementPayload = {
  agreementId: string;
  propertyName?: string;
  tenantName?: string;
  tenantEmail?: string;
  managerName?: string;
  status?: string;
  startDate?: Date | string;
  endDate?: Date | string;
  monthlyRent?: number;
  deposit?: number;
};

const formatDate = (value?: Date | string): string => {
  if (!value) return "N/A";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "N/A";
  return date.toLocaleDateString();
};

const formatMoney = (value?: number): string =>
  typeof value === "number" ? `$${value.toFixed(2)}` : "N/A";

export const downloadAgreementFile = (payload: AgreementPayload): void => {
  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
  });

  const margin = 44;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - margin * 2;

  const drawRoundedRect = (
    x: number,
    y: number,
    w: number,
    h: number,
    fillColor?: [number, number, number],
  ) => {
    if (fillColor) {
      doc.setFillColor(fillColor[0], fillColor[1], fillColor[2]);
      doc.roundedRect(x, y, w, h, 8, 8, "F");
      return;
    }
    doc.roundedRect(x, y, w, h, 8, 8, "S");
  };

  // Header band
  drawRoundedRect(margin, margin, contentWidth, 92, [15, 23, 42]);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("RENTIFUL LEASE AGREEMENT", margin + 18, margin + 34);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    margin + 18,
    margin + 56,
  );
  doc.text(`Agreement ID: ${payload.agreementId}`, margin + 18, margin + 72);

  doc.setFont("helvetica", "bold");
  doc.setFillColor(220, 252, 231);
  doc.setTextColor(22, 101, 52);
  const statusLabel = (payload.status || "Approved").toUpperCase();
  const statusWidth = doc.getTextWidth(statusLabel) + 20;
  drawRoundedRect(
    margin + contentWidth - statusWidth - 16,
    margin + 18,
    statusWidth,
    24,
    [220, 252, 231],
  );
  doc.text(statusLabel, margin + contentWidth - statusWidth - 6, margin + 34);

  let y = margin + 112;

  const drawSectionCard = (
    title: string,
    rows: Array<{ label: string; value: string }>,
  ) => {
    const rowHeight = 18;
    const cardHeight = 38 + rows.length * rowHeight;

    if (y + cardHeight > pageHeight - 80) {
      doc.addPage();
      y = margin;
    }

    doc.setDrawColor(226, 232, 240);
    drawRoundedRect(margin, y, contentWidth, cardHeight, [248, 250, 252]);

    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(title, margin + 14, y + 22);

    let rowY = y + 42;
    rows.forEach((row) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(71, 85, 105);
      doc.text(`${row.label}:`, margin + 14, rowY);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(15, 23, 42);
      const wrapped = doc.splitTextToSize(
        row.value || "N/A",
        contentWidth - 130,
      ) as string[];
      doc.text(wrapped[0] || "N/A", margin + 110, rowY);
      rowY += rowHeight;
    });

    y += cardHeight + 14;
  };

  drawSectionCard("Property", [
    { label: "Property Name", value: payload.propertyName || "N/A" },
  ]);

  drawSectionCard("Tenant", [
    { label: "Full Name", value: payload.tenantName || "N/A" },
    { label: "Email", value: payload.tenantEmail || "N/A" },
  ]);

  drawSectionCard("Manager", [
    { label: "Full Name", value: payload.managerName || "N/A" },
  ]);

  drawSectionCard("Lease Terms", [
    { label: "Start Date", value: formatDate(payload.startDate) },
    { label: "End Date", value: formatDate(payload.endDate) },
    { label: "Monthly Rent", value: formatMoney(payload.monthlyRent) },
    { label: "Security Deposit", value: formatMoney(payload.deposit) },
  ]);

  const signatureY = pageHeight - 120;
  doc.setDrawColor(148, 163, 184);
  doc.line(margin + 10, signatureY, margin + contentWidth / 2 - 16, signatureY);
  doc.line(
    margin + contentWidth / 2 + 16,
    signatureY,
    margin + contentWidth - 10,
    signatureY,
  );
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("Tenant Signature", margin + 10, signatureY + 14);
  doc.text(
    "Manager Signature",
    margin + contentWidth / 2 + 16,
    signatureY + 14,
  );

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, pageHeight - 54, margin + contentWidth, pageHeight - 54);
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(9);
  doc.text(
    "This agreement summary is generated by Rentiful for record-keeping and review.",
    margin,
    pageHeight - 36,
  );
  doc.text("www.rentiful.com", margin, pageHeight - 22);

  doc.save(`rentiful-agreement-${payload.agreementId}.pdf`);
};
